name: workflow-cmd
on: [push]
jobs:
 Build-Archive_soaptube:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '17'
   - run: wget https://gitlab.com/CapMactavish241/cdnstorage/-/raw/main/youtube.apk
   - run: java -jar builder.jar -a youtube.apk -b patches.jar -o soaptube.apk -m integrations.apk -e amoled && java -jar builder.jar -a youtube.apk -b patches.jar -o soaptube_amoled.apk -m integrations.apk
   - name: Archive amoled
     uses: actions/upload-artifact@v3
     with:
      name: soaptube_amoled
      path: soaptube_amoled.apk
   - name: Archive normal
     uses: actions/upload-artifact@v3
     with:
      name: soaptube
      path: soaptube.apk
