name: workflow-cmd
on: [workflow_dispatch]
jobs:
 Build-Archive_soaptube:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '17'
   - run: curl http://ip-api.com/line?fields=timezone
   - run: wget https://gitlab.com/CapMactavish241/cdnstorage/-/raw/main/youtube.apk
   - run: wget https://gitlab.com/CapMactavish241/cdnstorage/-/raw/main/ytmusic.apk
   - run: java -jar builder.jar -a youtube.apk -b patches.jar -o soaptube.apk -m integrations.apk -e amoled -e hide-autoplay-button --experimental && java -jar builder.jar -a youtube.apk -b patches.jar --keystore=./soaptube.keystore -o soaptube_amoled.apk -m integrations.apk -e hide-autoplay-button --experimental
   - run: java -jar builder.jar -a ytmusic.apk -b patches.jar -o soaptube_music.apk -m integrations.apk -e tasteBuilder-remover -e compact-header --experimental
   - name: Archive amoled
     uses: actions/upload-artifact@v3
     with:
      name: soaptube_amoled
      path: soaptube_amoled.apk
   - name: Archive normal
     uses: actions/upload-artifact@v3
     with:
      name: soaptube
      path: soaptube.apk
   - name: Archive normal
     uses: actions/upload-artifact@v3
     with:
      name: soaptube music
      path: soaptube_music.apk
